global:
  scrape_interval: 15s

# Set default port for scrapping
scrape_configs:
  - job_name: "node-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "pado-node"
    scrape_interval: 5s
    static_configs:
      # FORMAT container:port
      #   container: pado-node container name
      #        port: NODE_METRICS_PORT
      - targets: ["pado-network:9094"]
